### ISSUE TITLE
Deeper / more fine grained CSP findings

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-coordination#4105]
We should offer a normalizer for CSP headers that creates separate findings, each with their own severity-level and remarks for the various CSP issues.
Maybe, once normalizers can have configurations, we can merge them into one normalizer again.

**Comment by BramVWS** [comment]
@underdarknl 

# CSP Advice

Below is my initial input for the CSP configuration. It should, of course, be tweaked and QA tested, but I think this gives a good starting point.

My recommendation would be to create a hybrid configuration where we provide an initial setup. This allows organizations to tweak it to their own liking. For the initial configuration, I have combined the DigiD U/PW.03, Google CSP Evaluator, and the OWASP Secure Headers Project, and of course, the OpenKAT tweaks to make it even more secure.

## Best Practice

The best practice as defined by the iSDP is:
`Content-Security-Policy: default-src 'self'; form-action 'self'; object-src 'none'; frame-ancestors 'none'; base-uri 'none'; upgrade-insecure-requests;`

## Supported Headers

The following headers will be in the default configuration:

- base-uri
- child-src
- connect-src
- default-src
- font-src
- form-action
- frame-ancestors
- frame-src
- img-src
- manifest-src
- media-src
- object-src
- script-src
- script-src-attr
- script-src-elem
- style-src
- style-src-attr
- style-src-elem
- upgrade-insecure-requests
- worker-src

### Should Not Be Set

The following headers will be checked in the default configuration to ensure they are not set:

- block-all-mixed-content
- prefetch-src
- report-to
- report-uri

### Not Yet Included

The following headers are not set in the default configuration:

- fenced-frame-src
- require-trusted-types-for
- sandbox
- trusted-types

# Default Configuration

Below is an initial configuration file that contains the rules that should be followed for a proper CSP header.

The idea is as follows: let's say we have the CSP header `Content-Security-Policy: worker-src 'none' 'does_not_exist'; child-src http://example.com;`. It will split the elements and values and verify them with the configuration. In this case, we have the flags `worker-src` with the sub-values `'none'` and `'does_not_exist'`, and `child-src` with the value `http://example.com`.

When going through the configuration below, this means the output will be:

- `worker-src: 'none'` will not be included, as it is an expected value.
- `worker-src: 'does_not_exist'` will get the default severity "Low" as it is not defined.
- `child-src: http://example.com` will get the severity "Medium" as HTTP should not be used.
- finally all the elements or flag where expected_values is defined, which are not found will also trigger, e.g. base-uri 'none'; not set will be a high finding. 

This configuration can then be tweaked by an organization to be more in line with their policy and, of course, be improved by the community to have a secure default standard.

The finding can perhaps be added as one finding where the highest severity is used for the whole finding and detailed information deduced from the config is provided.

```yaml
default_severity: "Low"

base-uri:
    expected_values: ["'none'"]
    severity: "High"

block-all-mixed-content:
    non_expected_values: ["*"]
    severity: "Medium"

child-src:
    expected_values: ["'none'", "'self'", "'data'"]
    ignore_when: ["default-src: 'none'", "default-src: 'self'"]
    severity: "Medium"

child-src:
    non_expected_values: ["https://*"]
    severity: "Recommendation"

child-src:
    non_expected_values: ["http://*"]
    severity: "Medium"

connect-src:
    expected_values: ["'none'", "'self'"]
    ignore_when: ["default-src: 'none'", "default-src: 'self'"]
    severity: "Medium"

connect-src:
    non_expected_values: ["https://*"]
    severity: "Recommendation"

connect-src:
    non_expected_values: ["http://*"]
    severity: "Medium"

default-src:
    expected_values: ["'none'", "'self'"]
    severity: "High"

font-src:
    expected_values: ["'none'", "'self'"]
    ignore_when: ["default-src: 'none'", "default-src: 'self'"]
    severity: "Medium"

font-src:
    non_expected_values: ["https://*"]
    severity: "Recommendation"

font-src:
    non_expected_values: ["http://*"]
    severity: "Medium"

form-action:
    expected_values: ["'none'", "'self'"]
    severity: "Medium"

form-action:
    non_expected_values: ["https://*"]
    severity: "Recommendation"

form-action:
    non_expected_values: ["http://*"]
    severity: "Medium"

form-action:
    expected_values: ["'none'", "'self'"]
    severity: "Medium"

frame-ancestors:
    non_expected_values: ["https://*"]
    severity: "Recommendation"

frame-ancestors:
    non_expected_values: ["http://*"]
    severity: "Medium"

frame-src:
    expected_values: ["'none'", "'self'"]
    ignore_when: ["default-src: 'none'", "default-src: 'self'", "child-src: *;"]
    severity: "Medium"

frame-src:
    non_expected_values: ["https://*"]
    severity: "Recommendation"

frame-src:
    non_expected_values: ["http://*"]
    severity: "Medium"

img-src:
    expected_values: ["'none'", "'self'", "'data'"]
    ignore_when: ["default-src: 'none'", "default-src: 'self'"]
    severity: "Medium"

img-src:
    non_expected_values: ["https://*"]
    severity: "Recommendation"

img-src:
    non_expected_values: ["http://*"]
    severity: "Medium"

manifest-src:
    expected_values: ["'none'", "'self'"]
    ignore_when: ["default-src: 'none'", "default-src: 'self'"]
    severity: "Medium"

manifest-src:
    non_expected_values: ["https://*"]
    severity: "Recommendation"

manifest-src:
    non_expected_values: ["http://*"]
    severity: "Medium"

media-src:
    expected_values: ["'none'", "'self'"]
    ignore_when: ["default-src: 'none'", "default-src: 'self'"]
    severity: "Medium"

media-src:
    non_expected_values: ["https://*"]
    severity: "Recommendation"

media-src:
    non_expected_values: ["http://*"]
    severity: "Medium"

object-src:
    expected_values: ["'none'"]
    ignore_when: ["default-src: 'none'"]
    severity: "High"

block-all-mixed-content:
    non_expected_values: ["*"]
    severity: "Medium"

report-to:
    non_expected_values: ["*"]
    severity: "Recommendation"

report-uri:
    non_expected_values: ["*"]
    severity: "High"

script-src:
    expected_values: ["'none'", "'self'", "'nonce-*'", "'sha256-*'"]
    ignore_when: ["default-src: 'none'", "default-src: 'self'"]
    severity: "Medium"

script-src:
    non_expected_values: ["unsafe-eval"]
    severity: "Critical"

script-src:
    non_expected_values: ["unsafe-inline"]
    ignore_when: ["'strict-dynamic'"]
    severity: "High"

script-src:
    non_expected_values: ["https://*"]
    severity: "Recommendation"

script-src:
    non_expected_values: ["http://*"]
    severity: "High"

script-src-attr:
    expected_values: ["'none'", "'self'", "'nonce-*'", "'sha256-*'"]
    ignore_when: ["default-src: 'none'", "default-src: 'self'", script-src: *;]
    severity: "Medium"

script-src-attr:
    non_expected_values: ["https://*"]
    severity: "Recommendation"

script-src-attr:
    non_expected_values: ["http://*"]
    severity: "Medium"

script-src-elem:
    expected_values: ["'none'", "'self'", "'nonce-*'", "'sha256-*'"]
    ignore_when: ["default-src: 'none'", "default-src: 'self'", script-src: *;]
    severity: "Medium"

script-src-elem:
    non_expected_values: ["https://*"]
    severity: "Recommendation"

script-src-elem:
    non_expected_values: ["http://*"]
    severity: "Medium"

style-src:
    expected_values: ["'none'", "'self'", "'nonce-*'", "'sha256-*'"]
    ignore_when: ["default-src: 'none'", "default-src: 'self'"]
    severity: "Medium"

style-src:
    non_expected_values: ["unsafe-inline"]
    severity: "High"

style-src:
    non_expected_values: ["unsafe-hashes"]
    severity: "Medium"

style-src:
    non_expected_values: ["https://*"]
    severity: "Recommendation"

style-src:
    non_expected_values: ["http://*"]
    severity: "High"

style-src-attr:
    expected_values: ["'none'", "'self'", "'nonce-*'", "'sha256-*'"]
    ignore_when: ["default-src: 'none'", "default-src: 'self'", style-src: *;]
    severity: "Medium"

style-src-attr:
    non_expected_values: ["https://*"]
    severity: "Recommendation"

style-src-attr:
    non_expected_values: ["http://*"]
    severity: "Medium"

style-src-elem:
    expected_values: ["'none'", "'self'", "'nonce-*'", "'sha256-*'"]
    ignore_when: ["default-src: 'none'", "default-src: 'self'", style-src: *;]
    severity: "Medium"

style-src-elem:
    non_expected_values: ["https://*"]
    severity: "Recommendation"

style-src-elem:
    non_expected_values: ["http://*"]
    severity: "Medium"

upgrade-insecure-requests:
    expected_values: [""]
    severity: "Medium"

worker-src:
    expected_values: ["'none'", "'self'"]
    ignore_when: ["default-src: 'none'", "default-src: 'self'", "child-src: *;", "script-src: *"]
    severity: "Medium"

worker-src:
    non_expected_values: ["https://*"]
    severity: "Recommendation"

worker-src:
    non_expected_values: ["http://*"]
    severity: "Medium"

worker-src:
    non_expected_values: ["'blob:'"]
    severity: "Medium"
```
